<%@ Page Title="" Language="C#" MasterPageFile="~/AdminPanel.Master" AutoEventWireup="true" CodeBehind="MessagesAdmin.aspx.cs" Inherits="Porfolio_dynamic.MessagesAdmin" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <link href="css/gridstyle.css" rel="stylesheet" />
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="SectionControl" runat="server">
    <h3>Messages</h3>
            <asp:GridView ID="MsgGridView" CssClass="grid-view" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="true" OnRowDeleting="MsgGridView_RowDeleting">
                <Columns>
                    <asp:BoundField DataField="Name" HeaderText="NAME" />
                    <asp:BoundField DataField="Email" HeaderText="EMAIL" />
                    <asp:BoundField DataField="Message" HeaderText="MESSAGES" />                    
                </Columns>
            </asp:GridView>

    <asp:Label ID="HudaiLabel" runat="server" Text="" style="color:white;font-size:1.5rem;"></asp:Label>
    <asp:Button ID="backbtn" runat="server" Text="Back" Style="background-color: #00bbf9; padding: 10px 25px; border-radius: 25px;"
onmouseover="this.style.backgroundColor='#222';this.style.border='1px #fff solid';this.style.color='#fff';"
onmouseout="this.style.backgroundColor='#00bbf9';this.style.border='none';this.style.color='#000';" OnClick="backbtn_Click" />
</asp:Content>
